runtime: python
env: flex
entrypoint: gunicorn --worker-class eventlet -w 1 main:app

runtime_config:
  python_version: 3.6

manual_scaling:
  instances: 1

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

skip_files:
- git/

handlers:

- url: .*
  script: main.application

inbound_services:
- warmup
- channel_presence
